export const words = [
    { word: "Gato", clue: "Animal doméstico que suele decir 'miau'" },
    { word: "Perro", clue: "Animal leal conocido como el mejor amigo del hombre" },
    { word: "Casa", clue: "Edificación donde vive la gente" },
    { word: "Sol", clue: "Estrella alrededor de la cual orbita la Tierra" },
    { word: "Luna", clue: "Satélite natural de la Tierra" },
    { word: "Árbol", clue: "Planta con tronco leñoso y ramas" },
    { word: "Mesa", clue: "Mueble con una superficie plana y patas" },
    { word: "Silla", clue: "Asiento con respaldo y patas" },
    { word: "Zapato", clue: "Calzado que cubre el pie" },
    { word: "Pelota", clue: "Objeto esférico utilizado en diversos deportes" },
    { word: "Coche", clue: "Vehículo de cuatro ruedas utilizado para transporte" },
    { word: "Avión", clue: "Medio de transporte aéreo" },
    { word: "Barco", clue: "Embarcación utilizada para navegar en el agua" },
    { word: "Chocolate", clue: "Dulce hecho a base de cacao" },
    { word: "Café", clue: "Bebida caliente preparada a partir de granos de café" },
    { word: "Libro", clue: "Conjunto de hojas impresas y encuadernadas" },
    { word: "Computadora", clue: "Dispositivo electrónico utilizado para procesar información" },
    { word: "Teléfono", clue: "Dispositivo de comunicación que permite hablar a distancia" },
    { word: "Reloj", clue: "Instrumento para medir el tiempo" },
    { word: "Camisa", clue: "Prenda de vestir que cubre el torso" },
    { word: "Pantalón", clue: "Prenda de vestir que cubre las piernas" },
    { word: "Sombrero", clue: "Accesorio para cubrir la cabeza" },
    { word: "Paraguas", clue: "Objeto utilizado para protegerse de la lluvia" },
    { word: "Lápiz", clue: "Utensilio de escritura" },
    { word: "Papel", clue: "Material utilizado para escribir o imprimir" },
    { word: "Nube", clue: "Masa visible formada por gotas de agua suspendidas en la atmósfera" },
    { word: "Arcoíris", clue: "Fenómeno óptico y meteorológico que produce un espectro de luz" },
    { word: "Jirafa", clue: "Animal mamífero con cuello largo" },
    { word: "Elefante", clue: "Animal mamífero de gran tamaño con trompa" },
    { word: "León", clue: "Animal carnívoro conocido como el rey de la selva" },
    { word: "Tigre", clue: "Felino rayado de gran tamaño" },
    { word: "Cocodrilo", clue: "Reptil semiacuático con mandíbulas largas y dentadas" },
    { word: "Tortuga", clue: "Reptil con caparazón que vive tanto en agua como en tierra" },
    { word: "Ballena", clue: "Mamífero marino de gran tamaño" },
    { word: "Delfín", clue: "Mamífero marino inteligente y ágil" },
    { word: "Pingüino", clue: "Ave marina no voladora con plumaje negro y blanco" },
    { word: "Oso", clue: "Mamífero carnívoro de gran tamaño" },
    { word: "Cebra", clue: "Mamífero rayado blanco y negro" },
    { word: "Jirafa", clue: "Animal mamífero con cuello largo" },
    { word: "Elefante", clue: "Animal mamífero de gran tamaño con trompa" },
    { word: "León", clue: "Animal carnívoro conocido como el rey de la selva" },
    { word: "Tigre", clue: "Felino rayado de gran tamaño" },
    { word: "Cocodrilo", clue: "Reptil semiacuático con mandíbulas largas y dentadas" },
    { word: "Tortuga", clue: "Reptil con caparazón que vive tanto en agua como en tierra" },
        ]
